" Common editor settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set hlsearch
set incsearch
set number
filetype plugin indent on
syntax on

" Regenerate ctags on write
auto BufWritePost /opt/php-src/* silent! exec "!ctags -R -f /opt/tags /opt/php-src > /dev/null 2>/dev/null &"

set tags=./tags,tags;

" Key bindings
nnoremap ,t :w<CR>:!make -j8<CR>:!/opt/php-src/sapi/cli/php /opt/php-src/run-tests.php -x --offline %<CR>

